name: Transform Figma Tokens to CSS using Style Dictionary

# Controls when the workflow will run
on: [push, pull request]

permissions: write-all

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js Env
        uses: actions/setup-node@v2.4.0

      # Install Dependencies
      - run: npm install

      # Transform to CSS with SD
      - run: npm run transformToCSS

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: transformed FT to CSS with SD


